export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};

export const userConstants = {
  USER_REGISTRATION_REQUEST: 'USER_REGISTRATION_REQUEST',
  USER_REGISTRATION_SUCCESS: 'USER_REGISTRATION_SUCCESS',
  USER_REGISTRATION_FAILURE: 'USER_REGISTRATION_FAILURE',
};

export const categoryConstants = {
  GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
  GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
  GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',
  ADD_NEW_CATEGORY_REQUEST: 'ADD_NEW_CATEGORY_REQUEST',
  ADD_NEW_CATEGORY_SUCCESS: 'ADD_NEW_CATEGORY_SUCCESS',
  ADD_NEW_CATEGORY_FAILURE: 'ADD_NEW_CATEGORY_FAILURE',
};

export const productConstants = {
  ADD_NEW_PRODUCT_REQUEST: 'ADD_NEW_PRODUCT_REQUEST',
  ADD_NEW_PRODUCT_SUCCESS: 'ADD_NEW_PRODUCT_SUCCESS',
  ADD_NEW_PRODUCT_FAILURE: 'ADD_NEW_PRODUCT_FAILURE',
};
